name: Python Code Review Bot

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install flake8 bandit requests

      - name: Extract PR Number
        run: echo "PR_NUMBER=$(jq --raw-output '.pull_request.number' "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV

      - name: Run Linter (Flake8)
        run: |
          echo "Running Flake8 Linter..."
          flake8 --format=json --output-file=flake8_report.json . || echo "FLAKE8_FAILED=true" >> $GITHUB_ENV

      - name: Run Security Scan (Bandit)
        run: |
          echo "Running Bandit Security Scan..."
          bandit -r . -f json -o bandit_report.json || echo "BANDIT_FAILED=true" >> $GITHUB_ENV

      - name: Show Flake8 Report
        if: always()
        run: |
          echo "🔍 Flake8 Report:"
          jq . flake8_report.json || cat flake8_report.json || echo "No Flake8 report found."

      - name: Show Bandit Report
        if: always()
        run: |
          echo "🔍 Bandit Report:"
          jq . bandit_report.json || cat bandit_report.json || echo "No Bandit report found."


      - name: Run Review Bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
        run: python .github/workflows/review_bot.py

      - name: Final Job Status
        run: |
          if [[ "$FLAKE8_FAILED" == "true" || "$BANDIT_FAILED" == "true" ]]; then
            echo "❌ Linting or Security scan failed. Check the logs above."
            exit 1
          else
            echo "✅ All checks passed."
          fi
