name: Python Code Review Bot

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install flake8 bandit requests

      - name: Extract PR Number
        run: echo "PR_NUMBER=$(jq --raw-output '.pull_request.number' "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV

      - name: Run Linter (Flake8)
        run: flake8 --format=json --output-file=flake8_report.json . || true

      - name: Run Security Scan (Bandit)
        run: bandit -r . -f json -o bandit_report.json || true

      - name: Debug GitHub Environment
        run: echo "GITHUB_TOKEN is available"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Review Bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
        run: python .github/workflows/review_bot.py
