name: Python Code Review Bot

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install flake8 bandit requests

      - name: Extract PR Number
        run: echo "PR_NUMBER=$(jq --raw-output '.pull_request.number' "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV

      - name: Run Linter (Flake8)
        run: |
          echo "Running Flake8 Linter..."
          flake8 . || echo "FLAKE8_FAILED=true" >> $GITHUB_ENV

      - name: Print Current Working Directory
        run: |
          echo "Current working directory:"
          pwd

      - name: Run Linter (Flake8)
        run: |
          echo "Running Flake8 Linter..."
          python -m flake8 --format=json --output-file=flake8_report.json . || true
          
      - name: Check if Flake8 Report is Generated
        run: |
          echo "Checking for generated Flake8 report..."
          if [ -f flake8_report.json ]; then
            echo "✅ Flake8 report generated successfully at $(pwd)/flake8_report.json."
          else
            echo "❌ Flake8 report not found at $(pwd)/flake8_report.json!"
            exit 1
          fi


      - name: Run Security Scan (Bandit)
        run: |
          echo "Running Bandit Security Scan..."
          bandit -r . || echo "BANDIT_FAILED=true" >> $GITHUB_ENV

      - name: Run Review Bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
        run: python .github/workflows/review_bot.py

      - name: Final Job Status for Linting
        run: |
          if [[ "$FLAKE8_FAILED" == "true" ]]; then
            echo "❌ Linting failed. Check the logs above."
            exit 1
          else
            echo "✅ Linting check passed."
          fi

      - name: Final Job Status Security Scan
        run: |
          if [[ "$BANDIT_FAILED" == "true" ]]; then
            echo "❌ Security scan failed. Check the logs above."
            exit 1
          else
            echo "✅ Security Scan passed."
          fi
